### ISSUE TITLE
KeyError: 'score'

### ISSUE THREAD

**Issue by storniai** [kolonen/surprise#27]
I get the following error when running the run_client.py:

Traceback (most recent call last):
  File "run_client.py", line 13, in <module>
    wagers = wc.get_wagers(s)
  File "../server/wager_client.py", line 27, in get_wagers
    return get_wagers_by_txs(session,tx_ids)
  File "../server/wager_client.py", line 37, in get_wagers_by_txs
    wagers = map(lambda w: parse_wager(w),wagers)
  File "../server/wager_client.py", line 37, in <lambda>
    wagers = map(lambda w: parse_wager(w),wagers)
  File "../server/wager_client.py", line 75, in parse_wager
    ), selections)
  File "../server/wager_client.py", line 73, in <lambda>
    home_score=rows[i]['result']['score']['home'],
KeyError: 'score'

Platform: OS X El Capitan (Version 10.11.4)

**Comment by storniai** [comment]
Looks like the problem is in data. One event of a wager does not contain key "score", as shown below:

9: {u'status': u'RESULTS_AVAILABLE', u'eventId': u'87530088', u'additionalPrizeTier': False, u'result': {u'status': u'PRELIMINARY', u'outcome': {u'away': True}, u'decided': True}, u'outcome': {u'home': {u'id': u'Blackburn', u'name': u'Blackburn'}, u'away': {u'id': u'Middlesbr', u'name': u'Middlesbrough'}}, u'id': u'9'},

**Comment by storniai** [comment]
fixed
